### ISSUE TITLE
Layers missing in /sky130_tech/tech/sky130/sky130.lyp file

### ISSUE THREAD

**Issue by DavidRLindley** [efabless/sky130_klayout_pdk#17]
These layers are in the post tapeout Caravel layout.  They need to be added to the sky130.lyp file.

layer     datatype     purpose
23         28          added cfom waffles
28         28          added cp1m waffles
34         28          added cmm3 waffles
36         28          added cmm1 waffles
41         28          added cmm2 waffles
51         28          added cmm4 waffles
56         28          added cli1m waffles
59         28          added cmm5 waffles
79         20          URPM
83         44          text drawing
235        0           open source ram cell core areaid
236        0           boundary

These layers are in the proprietary IP we just received.  They also need to be added to the sky130.lyp file
layer     datatype     purpose
235        252         boundary
235        250         boundary

**Comment by DavidRLindley** [comment]
Leo, was the layers file pushed to the repo?  If so, please close this.

**Comment by mole99** [comment]
Yes, I forgot to reference this issue!
