### ISSUE TITLE
pymacros module import error: gdsfactory.types is missing

### ISSUE THREAD

**Issue by martinjankoehler** [efabless/sky130_klayout_pdk#20]
## Expected Behavior

`sky130_tech/tech/sky130/pymacros/sky130.lym` macro to properly load on klayout startup with technology installed.

## Actual Behavior

Python module import error: 
![image](https://github.com/efabless/sky130_klayout_pdk/assets/29398377/520300fc-7f80-4cfe-9520-261e497eb7d5)

## Steps to Reproduce the Problem

1. Update gdsfactory to a recent version `pip install --upgrade gdsfactory`
1. Start klayout, install the sky130 technology
1. Start again, the import error is reported

## Specifications

- Volare PDK Version: `├── PRE-RELEASE 31f6da2663f392b7472bdba39c1746170d293290 (2024.05.25) (enabled)`
- Platform: MacOS 10.14 and Ubuntu
- Python: 3.12.3
- gdsfactory 7.27.0
- klayout: 0.29.1

**Comment by martinjankoehler** [comment]
With this Feature Branch the problem is fixed:
https://github.com/martinjankoehler/sky130_klayout_pdk/tree/gdsfactory-types-fix

**Comment by mole99** [comment]
Hi @martinjankoehler, thanks for the report and a potential fix!

Unfortunately, I am not sure that this works for the PCells. Last time I had a look at this, the changes allowed to load the pymacros, but the PCells failed to generate.

For now I have tried to pin `gdsfactory` and `pydantic` to an older version as seen here: https://codeberg.org/mole99/klayout-sky130-inverter
But that should at least be documented, and in the best case the PCells should be fixed to work with the latest `gdsfactory` version. TBD!

**Comment by martinjankoehler** [comment]
Hi @mole99,

the branch is now updated, merged additional fixes and refactorings from @klayoutmatthias PR https://github.com/martinjankoehler/sky130_klayout_pdk/pull/1

**Comment by mole99** [comment]
That's great @martinjankoehler!

Can you open a PR against this repo, so we can merge it here too? Thanks!

**Comment by martinjankoehler** [comment]
@mole99 de one, see PR #21
