### ISSUE TITLE
ImportError: cannot import name 'Qt' from 'pya' (/../lib/python3.8/site-packages/pya/__init__.py)

### ISSUE THREAD

**Issue by mguthaus** [efabless/sky130_klayout_pdk#29]
## Expected Behavior

When running the LVS scripts, I expect a Qt popup window.

## Actual Behavior

I'm using a recent version of KLayout (0.29.10) but it seems to have a problem importing the Qt objects used in the LVS scripts. I'm not sure if this is a KLayout compilation issue and what options the LVS scripts require for building it. I also filed an issue on the KLayout forum [here](https://www.klayout.de/forum/discussion/2640/importerror-cannot-import-name-qt-from-pya-lib-python3-8-site-packages-pya-init-py/p1).

## Steps to Reproduce the Problem

Starting LVS causes the issue before the first menu even pops up. I can also replicate with the following:

>  ~/temp (master)$ python3 -m venv .venv
>  ~/temp (master)$ source .venv/bin/activate
> (.venv) ~/temp (master)$ python3 -m pip install klayout
> Collecting klayout
>   Using cached klayout-0.29.10-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.8 MB)
> Installing collected packages: klayout
> Successfully installed klayout-0.29.10
> (.venv)  ~/temp (master)$ python3
> Python 3.8.10 (default, Jul 29 2024, 17:02:10)
> [GCC 9.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> import pya
> from pya import Qt
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'Qt' from 'pya' (/home/mrg/temp/.venv/lib/python3.8/site-packages/pya/__init__.py)

## Specifications

- Version: 
- Platform: Ubuntu 20.04/Python 3.8

**Comment by mole99** [comment]
Hi @mguthaus, thanks for your report. From the issue on the KLayout forum, I figure that the standalone Python module does not support Qt. Therefore, this issue can only be reproduced when executing the pymacro in KLayout via the "Efabless sky130" menu.

How did you install KLayout?

You can install a fully-featured KLayout (with gdsfactory enabled for the PCells) using Nix. Simply install Nix and Efabless's Nix cache by following this guide: https://cace.readthedocs.io/en/latest/getting_started/common/nix_installation/index.html

Afterwards, you can start KLayout in editable mode with this command:

```
nix run github:efabless/nix-eda#klayout-gdsfactory -- -e
```

This repository hosts a variety of Nix derivations: https://github.com/efabless/nix-eda/tree/main

**Comment by mguthaus** [comment]
Cool, thanks for the tip.
