### ISSUE TITLE
XML error when loading lvs macros

### ISSUE THREAD

**Issue by proppy** [efabless/sky130_klayout_pdk#7]
## Expected Behavior

lvs macro are being loaded without error.

## Actual Behavior

The following error occur on startup when loading lvs macros:
```
ERROR: Reading /home/proppy/mixed-signal-sky130a-env/share/pdk/sky130A/libs.tech/klayout/lvs/sky130.lylvs: XML parser error: not well-formed (invalid token) in line 31, column 48
```

This is likely due to character not being escaped in the license text included in the LVS XML, see:
https://github.com/efabless/sky130_klayout_pdk/blob/5e6e2b29d2b9f8d0f2de1b5d5f649f33017dac75/sky130_tech/tech/sky130/lvs/sky130.lylvs#L31

**Comment by mole99** [comment]
Hi @proppy! This was fixed by #11. If any other issues come up,  feel free to open an issue :+1: 
(I'm currently trying to clean up this repo a bit)
